version: '3.9'
services:
  stories:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    platform: linux/amd64/v8
    environment:
      PORT: 5081
      INDEX_TYPE: serverless
      DIMENSION: 384
      METRIC: cosine
    ports:
      - '5081:5081'
  stories-inverse:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    platform: linux/amd64/v8
    environment:
      PORT: 5082
      INDEX_TYPE: serverless
      DIMENSION: 2
      METRIC: euclidean
    ports:
      - '5082:5082'
  mysql:
    image: mysql:latest
    container_name: max-entropy-news-mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=max-entropy-news-db
      - MYSQL_ROOT_PASSWORD=password
      - MSSQL_AGENT_ENABLED=true
    ports:
      - '3369:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
