version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: max-entropy-news-mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=max-entropy-news-db
      - MYSQL_ROOT_PASSWORD=password
      - MSSQL_AGENT_ENABLED=true
    ports:
      - '3369:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
